### ISSUE TITLE
Function Image fails to launch the browser process

### ISSUE THREAD

**Issue by SGiumelli** [Resocio/resoc-netlify-image-engine#1]
What happens :
No image is returned

Version:
- node 16
- aws node 16

```
Sep 29, 10:07:58 PM: cdfdb004 INFO   Error: Failed to launch the browser process!
Sep 29, 10:07:58 PM: cdfdb004 INFO   /tmp/chromium: error while loading shared libraries: libnss3.so: cannot open shared object file: No such file or directory
Sep 29, 10:07:58 PM: cdfdb004 INFO   TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
Sep 29, 10:07:58 PM: cdfdb004 INFO       at onClose (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:197:20)
Sep 29, 10:07:58 PM: cdfdb004 INFO       at Interface.<anonymous> (/var/task/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:187:68)
Sep 29, 10:07:58 PM: cdfdb004 INFO       at Interface.emit (node:events:539:35)
Sep 29, 10:07:58 PM: cdfdb004 INFO       at Interface.close (node:readline:586:8)
Sep 29, 10:07:58 PM: cdfdb004 INFO       at Socket.onend (node:readline:277:10)
Sep 29, 10:07:58 PM: cdfdb004 INFO       at Socket.emit (node:events:539:35)
Sep 29, 10:07:58 PM: cdfdb004 INFO       at endReadableNT (node:internal/streams/readable:1345:12)
Sep 29, 10:07:58 PM: cdfdb004 INFO       at processTicksAndRejections (node:internal/process/task_queues:83:21)
Sep 29, 10:07:58 PM: cdfdb004 Duration: 45.40 ms	Memory Usage: 379 MB
```

# to reproduce
- use template
- clone repo
- push and deploy to Netlfy
- request any image (demo included)

(this resocio is a very nice thing btw, i love it ❤️ )

**Comment by SGiumelli** [comment]
Atm i managed to make it work by setting ENV in netlify :
`AWS_LAMBDA_JS_RUNTIME=nodejs14.x`
